.TH NWEB 8 "June 19, 2017"
.SH NAME
nweb \- small and very safe mini web server
.SH SYNPOSIS
.B nweb
[\fIport\fR]
[\fItopdir\fR]
.SH DESCRIPTION
nweb only servers out file/web pages with extensions named below and only from the named directory or its sub-directories.

There is no fancy features = safe and secure.

Only Supports: gif jpg jpeg png ico zip gz tar htm html

Not Supported: URLs including "..", Java, Javascript, CGI

Not Supported: directories / /etc /bin /lib /tmp /usr /dev /sbin

No warranty given or implied

Nigel Griffiths nag@uk.ibm.com
.SH EXAMPLES
 "nweb 8181 /srv/www &"

Runs nweb on port 8181 serving files in /srv/www
